/** 36 states + FCT */
export const NIGERIA_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type NigeriaState = (typeof NIGERIA_STATES)[number];

export const GENDERS = ["Male", "Female"] as const;

/** Ekiti LGAs (primary for married-women / posting forms) */
export const EKITI_LGAS = [
  "Ado Ekiti",
  "Efon",
  "Ekiti East",
  "Ekiti South-West",
  "Ekiti West",
  "Emure",
  "Gbonyin",
  "Ido Osi",
  "Ijero",
  "Ikere",
  "Ikole",
  "Ilejemeje",
  "Irepodun/Ifelodun",
  "Ise/Orun",
  "Moba",
  "Oye",
] as const;
